import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <main className={`${styles.main}`}>
        <h1 className={styles.title}>
          Coding Blogs
        </h1>
        <p className={styles.description}>
         Where you can learn new concepts about Coding
        </p>
        
       <h3>best languages </h3>
       <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum dolorum illo.</p>
       <h3>best languages </h3>
       <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum dolorum illo.</p> <h3>best languages </h3>
       <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum dolorum illo.</p> <h3>best languages </h3>
       <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum dolorum illo.</p> <h3>best languages </h3>
       <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Sapiente harum dolorum illo.</p>
  
       
      </main>
    </>
  )
}
